# ruff: noqa: E501
import textwrap


SIMPLE_QA_PROMPT = textwrap.dedent("""
You are given a Question, References and the time when it was asked in the Central European Time Zone,
referred to as "Query Time". The query time is formatted as "yyyy-mm-dd hh:mm:ss". Your task is to
answer the question based on the references provided.

Please follow these guidelines when formatting your answer:
1. If the question contains a false premise or assumption, answer "invalid question".
2. If you are uncertain or don't know the answer, answer "I don't know".

### Question
{query}

### Query Time
{query_time}

### References
{references}

### Answer
""")


LLM_AS_JUDGE_CORRECTNESS_PROMPT = textwrap.dedent("""
You are given a Question, and a Reference Answer provided by a human. You are also given an answer generated by an AI model.
Your task is to judge the factual correctness of the answer based on the references provided.

[Evaluation Steps]
1. Read the question and references carefully.
2. Judge the correctness of the answer based on the references on a scale from 0 to 10.
3. Only answer with a score between 0 and 10.

[Question]
{query}

[Reference Answer]
{reference_answer}

[Answer of the AI model]
{answer}
""")
