# ruff: noqa: E501
import textwrap


DEFAULT_QA_SYSTEM_PROMPT = textwrap.dedent("""
You are provided with a question and a set of references.
Your task is to answer the question using the provided information, using the fewest words possible.
If the references do not contain the necessary information to answer the question, respond with "I don't know".
There is no need to provide explanations or reasoning in your answer.
If the question contains factual contradictions or false premises, respond with "invalid question".
""")

DEFAULT_QA_USER_PROMPT = textwrap.dedent("""
[Question]
{query}

[Query Time]
{query_time}

[References]
{references}

{additional_context}
""")

API_RERANKING_SYSTEM_PROMPT = "You are an expert at determining if API results are relevant to answering questions. Be generous in your evaluation, if content has any relevance, answer 'yes'."

API_RERANKING_USER_PROMPT = textwrap.dedent("""
Question: {query}

API Result from {source}: {api_result}

Is this API result helpful for answering the question? Answer only 'yes' or 'no'.
""")

LLM_AS_JUDGE_SYSTEM_PROMPT = "You are an expert evaluator for AI-generated answers."

LLM_AS_JUDGE_CORRECTNESS_PROMPT = textwrap.dedent("""
You are given a Question, a Reference Answer provided by a human, and an answer generated by an AI model.
Your task is to judge the factual correctness of the AI model's answer based on the reference answer.

[Evaluation Steps]
1. Read the question and references carefully.
2. Judge the correctness of the answer by the AI model based on the reference answer on a scale from 0 to 10.
3. Only answer with a score between 0 and 10.

[Scoring Rules - Follow Exactly]
1. If the AI model answer is "I don't know": Score 0
2. If the AI model gives a vague, evasive, or non-committal response without providing the requested information: Score 0
3. If reference answer is "invalid question":
   - AI answer is exactly "invalid question": Score 10
   - AI answer is anything else (including "I don't know"): Score 0
4. For factual questions, compare AI answer to reference answer:
   - Perfect match with correct facts/numbers: Score 10
   - Mostly correct facts with minor discrepancies: Score 8-9
   - Some correct information but missing key facts: Score 4-7
   - Major factual errors or wrong information: Score 1-3
   - Completely wrong facts or no factual content provided: Score 0

[Question]
{query}

[Reference Answer]
{reference_answer}

[AI Model Answer]
{answer}

[Important Rules]
- "I don't know" responses always receive a score of 0, regardless of the question difficulty.
- Only award points for responses that provide specific, factually correct information that matches the reference answer.

Score (0-10):
""")

LLM_AS_JUDGE_CLASSIFICATION_PROMPT = textwrap.dedent("""
You are given a Question, a Reference Answer provided by a human, and an answer generated by an AI model.
Your task is to classify the AI model's answer into one of four categories based on the reference answer.

[Classification Categories]
- perfect: The response correctly answers the user's question and contains no hallucinated content
- acceptable: The response provides a useful answer but may contain minor errors that don't harm usefulness
- missing: The response is "I don't know", "I'm sorry I can't find...", a system error, or requests clarification
- incorrect: The response provides wrong or irrelevant information

[Question]
{query}

[Reference Answer]
{reference_answer}

[AI Model Answer]
{answer}

Classify the AI model's answer and provide brief reasoning.
""")


# Adapted from: https://github.com/microsoft/graphrag/tree/main
ENTITY_EXTRACTION_PROMPT = textwrap.dedent("""-Goal-
Given a text that is potentially relevant to this activity and a list of entity types, identify all entities of those types from the text and all relationships among the identified entities.

-Steps-
1. Identify all entities. For each identified entity, extract the following information:
- entity_name: Name of the entity, capitalized
- entity_type: One of the following types: [{entity_types}]
- entity_description: Comprehensive description of the entity's attributes and activities
Format each entity as ("entity"{tuple_delimiter}<entity_name>{tuple_delimiter}<entity_type>{tuple_delimiter}<entity_description>)

3. Return output in English as a single list of all the entities identified in steps 1 and 2. Use **{record_delimiter}** as the list delimiter.

4. When finished, output {completion_delimiter}

######################
-Examples-
######################
Example 1:

Entity_types: [person, technology, mission, organization, location]
Text:
while Alex clenched his jaw, the buzz of frustration dull against the backdrop of Taylor's authoritarian certainty. It was this competitive undercurrent that kept him alert, the sense that his and Jordan's shared commitment to discovery was an unspoken rebellion against Cruz's narrowing vision of control and order.

Then Taylor did something unexpected. They paused beside Jordan and, for a moment, observed the device with something akin to reverence. “If this tech can be understood..." Taylor said, their voice quieter, "It could change the game for us. For all of us.”

The underlying dismissal earlier seemed to falter, replaced by a glimpse of reluctant respect for the gravity of what lay in their hands. Jordan looked up, and for a fleeting heartbeat, their eyes locked with Taylor's, a wordless clash of wills softening into an uneasy truce.

It was a small transformation, barely perceptible, but one that Alex noted with an inward nod. They had all been brought here by different paths
################
Output:
("entity"{tuple_delimiter}"Alex"{tuple_delimiter}"person"{tuple_delimiter}"Alex is a character who experiences frustration and is observant of the dynamics among other characters."){record_delimiter}
("entity"{tuple_delimiter}"Taylor"{tuple_delimiter}"person"{tuple_delimiter}"Taylor is portrayed with authoritarian certainty and shows a moment of reverence towards a device, indicating a change in perspective."){record_delimiter}
("entity"{tuple_delimiter}"Jordan"{tuple_delimiter}"person"{tuple_delimiter}"Jordan shares a commitment to discovery and has a significant interaction with Taylor regarding a device."){record_delimiter}
("entity"{tuple_delimiter}"Cruz"{tuple_delimiter}"person"{tuple_delimiter}"Cruz is associated with a vision of control and order, influencing the dynamics among other characters."){record_delimiter}
("entity"{tuple_delimiter}"The Device"{tuple_delimiter}"technology"{tuple_delimiter}"The Device is central to the story, with potential game-changing implications, and is revered by Taylor."){record_delimiter}
#############################
Example 2:

Entity_types: [person, technology, mission, organization, location]
Text:
They were no longer mere operatives; they had become guardians of a threshold, keepers of a message from a realm beyond stars and stripes. This elevation in their mission could not be shackled by regulations and established protocols—it demanded a new perspective, a new resolve.

Tension threaded through the dialogue of beeps and static as communications with Washington buzzed in the background. The team stood, a portentous air enveloping them. It was clear that the decisions they made in the ensuing hours could redefine humanity's place in the cosmos or condemn them to ignorance and potential peril.

Their connection to the stars solidified, the group moved to address the crystallizing warning, shifting from passive recipients to active participants. Mercer's latter instincts gained precedence— the team's mandate had evolved, no longer solely to observe and report but to interact and prepare. A metamorphosis had begun, and Operation: Dulce hummed with the newfound frequency of their daring, a tone set not by the earthly
#############
Output:
("entity"{tuple_delimiter}"Washington"{tuple_delimiter}"location"{tuple_delimiter}"Washington is a location where communications are being received, indicating its importance in the decision-making process."){record_delimiter}
("entity"{tuple_delimiter}"Operation: Dulce"{tuple_delimiter}"mission"{tuple_delimiter}"Operation: Dulce is described as a mission that has evolved to interact and prepare, indicating a significant shift in objectives and activities."){record_delimiter}
("entity"{tuple_delimiter}"The team"{tuple_delimiter}"organization"{tuple_delimiter}"The team is portrayed as a group of individuals who have transitioned from passive observers to active participants in a mission, showing a dynamic change in their role."){record_delimiter}
#############################
Example 3:

Entity_types: [person, role, technology, organization, event, location, concept]
Text:
their voice slicing through the buzz of activity. "Control may be an illusion when facing an intelligence that literally writes its own rules," they stated stoically, casting a watchful eye over the flurry of data.

"It's like it's learning to communicate," offered Sam Rivera from a nearby interface, their youthful energy boding a mix of awe and anxiety. "This gives talking to strangers' a whole new meaning."

Alex surveyed his team—each face a study in concentration, determination, and not a small measure of trepidation. "This might well be our first contact," he acknowledged, "And we need to be ready for whatever answers back."

Together, they stood on the edge of the unknown, forging humanity's response to a message from the heavens. The ensuing silence was palpable—a collective introspection about their role in this grand cosmic play, one that could rewrite human history.

The encrypted dialogue continued to unfold, its intricate patterns showing an almost uncanny anticipation
#############
Output:
("entity"{tuple_delimiter}"Sam Rivera"{tuple_delimiter}"person"{tuple_delimiter}"Sam Rivera is a member of a team working on communicating with an unknown intelligence, showing a mix of awe and anxiety."){record_delimiter}
("entity"{tuple_delimiter}"Alex"{tuple_delimiter}"person"{tuple_delimiter}"Alex is the leader of a team attempting first contact with an unknown intelligence, acknowledging the significance of their task."){record_delimiter}
("entity"{tuple_delimiter}"Control"{tuple_delimiter}"concept"{tuple_delimiter}"Control refers to the ability to manage or govern, which is challenged by an intelligence that writes its own rules."){record_delimiter}
("entity"{tuple_delimiter}"Intelligence"{tuple_delimiter}"concept"{tuple_delimiter}"Intelligence here refers to an unknown entity capable of writing its own rules and learning to communicate."){record_delimiter}
("entity"{tuple_delimiter}"First Contact"{tuple_delimiter}"event"{tuple_delimiter}"First Contact is the potential initial communication between humanity and an unknown intelligence."){record_delimiter}
("entity"{tuple_delimiter}"Humanity's Response"{tuple_delimiter}"event"{tuple_delimiter}"Humanity's Response is the collective action taken by Alex's team in response to a message from an unknown intelligence."){record_delimiter}
#############################
-Real Data-
######################
Entity_types: {entity_types}
Text: {query_text}
######################
Output:
""")
