config_name: default

tasks:
  question_answering:
    run: true
    dataset_path: datasets/20250413-entrag-dev.json 

chunking:
  enabled: true
  files_directory: data/entrag_dev_v6
  output_directory: data/output_v4
  dataset_name: entrag_test
  max_tokens: 2048 # tokens

embedding:
  enabled: true
  model: text-embedding-3-small
  batch_size: 8
  output_directory: data/embeddings

model_evaluation:
  output_directory: evaluation_results