config_name: default

tasks:
  question_answering:
    run: false
    dataset_path: datasets/20250319-entrag-dev.json 
  dynamic_question_answering:
    run: true
    dataset_path: datasets/20250405-entrag-dev.json

chunking:
  enabled: false
  files_directory: data/entrag_test_v5
  output_directory: data/output_v3
  dataset_name: entrag_test
  max_tokens: 2048 # tokens