config_name: default

tasks:
  question_answering:
    run: true
    hf_dataset_id: fkapsahili/EntRAG
    dataset_path: null
    split: train

chunking:
  enabled: true
  files_directory: data/entrag_processed
  output_directory: data/entrag_chunked
  dataset_name: entrag
  max_tokens: 2048 # tokens

embedding:
  enabled: true
  model: text-embedding-3-small
  batch_size: 8
  output_directory: data/embeddings

model_evaluation:
  max_workers: 10 # Number of parallel workers for LLM inference
  output_directory: evaluation_results
  retrieval_top_k: 5
  model_provider: openai
  model_name: gpt-4.1-mini
  reranking_model_name: gpt-4.1-mini # Must be one of: gpt-4o-mini, gpt-4.1-nano, gpt-4.1-mini