config_name: default_test

chunks:
  model_name: sentence-transformers/all-MiniLM-L6-v2
  min_tokens: 256 # tokens
  target_chunk_size: 512 # tokens
  max_tokens: 1024 # tokens
  similarity_threshold: 0.3