[project]
name = "entrag-mock-api"
version = "0.0.0"
description = "EntRAG Mock API interfaces"
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "beautifulsoup4>=4.13.3",
    "click>=8.1.8",
    "fastapi>=0.115.12",
    "fastparquet>=2024.11.0",
    "loguru>=0.7.3",
    "pandas>=2.2.3",
    "pyarrow>=20.0.0",
    "pydantic>=2.10.6",
    "requests>=2.32.3",
    "uvicorn>=0.34.0",
    "yfinance>=0.2.55",
]

[project.scripts]
start = "entrag_mock_api.main:start"

[tool.ruff]
extend = "../../pyproject.toml"
exclude = ["build", "dist"]
include = ["src/**"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/entrag_mock_api"]
