[project]
name = "entrag-mock-api"
version = "0.0.0"
description = "EntRAG Mock API interfaces"
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "click>=8.1.8",
    "fastapi>=0.115.12",
    "loguru>=0.7.3",
    "yfinance>=0.2.55",
]

[tool.ruff]
extend = "../../pyproject.toml"
exclude = ["build", "dist"]
include = ["src/**"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/entrag_mock_api"]
